const codesData = [
  {
    table_name: "transactions",
    table_column: "status",
    value: 0,
    meaning: "Pending",
  },
  {
    table_name: "transactions",
    table_column: "status",
    value: 1,
    meaning: "Success",
  },
  {
    table_name: "transactions",
    table_column: "status",
    value: 2,
    meaning: "Fail",
  },
  {
    table_name: "transactions",
    table_column: "type",
    value: 0,
    meaning: "Normal",
  },
  {
    table_name: "transactions",
    table_column: "type",
    value: 1,
    meaning: "Create contract",
  },
  {
    table_name: "transactions",
    table_column: "type",
    value: 2,
    meaning: "ERC-20",
  },
  {
    table_name: "transactions",
    table_column: "type",
    value: 3,
    meaning: "NFT",
  },
  {
    table_name: "transactions",
    table_column: "type",
    value: 4,
    meaning: "Evidence",
  },
  {
    table_name: "public_tags",
    table_column: "target_type",
    value: 0,
    meaning: "contract",
  },
  {
    table_name: "public_tags",
    table_column: "target_type",
    value: 1,
    meaning: "address",
  },
  {
    table_name: "evidences",
    table_column: "state",
    value: 0,
    meaning: "public",
  },
  {
    table_name: "evidences",
    table_column: "state",
    value: 1,
    meaning: "private",
  },
  {
    table_name: "review_datas",
    table_column: "target_type",
    value: 0,
    meaning: "address",
  },
  {
    table_name: "review_datas",
    table_column: "target_type",
    value: 1,
    meaning: "transaction",
  },
  {
    table_name: "red_flags",
    table_column: "red_flag_type",
    value: 0,
    meaning: "Multiple Transfer",
  },
  {
    table_name: "red_flags",
    table_column: "red_flag_type",
    value: 1,
    meaning: "Multiple Receives",
  },
  {
    table_name: "red_flags",
    table_column: "red_flag_type",
    value: 2,
    meaning: "Large Deposit",
  },
  {
    table_name: "red_flags",
    table_column: "red_flag_type",
    value: 3,
    meaning: "With Mixing Service",
  },
  {
    table_name: "red_flags",
    table_column: "red_flag_type",
    value: 4,
    meaning: "Multiple Withdraw",
  },
  {
    table_name: "red_flags",
    table_column: "red_flag_type",
    value: 5,
    meaning: "With Gambling Site",
  },
  {
    table_name: "red_flags",
    table_column: "red_flag_type",
    value: 6,
    meaning: "Large Withdraw",
  },
  {
    table_name: "red_flags",
    table_column: "red_flag_type",
    value: 7,
    meaning: "With Black List",
  },
  {
    table_name: "red_flags",
    table_column: "red_flag_type",
    value: 8,
    meaning: "With Darknet",
  },
  {
    table_name: "red_flags",
    table_column: "red_flag_type",
    value: 9,
    meaning: "Large Transfer",
  },
  {
    table_name: "currencies",
    table_column: "risk_level",
    value: 0,
    meaning: "Low",
  },
  {
    table_name: "currencies",
    table_column: "risk_level",
    value: 1,
    meaning: "Normal",
  },
  {
    table_name: "currencies",
    table_column: "risk_level",
    value: 2,
    meaning: "High",
  },
];

export default codesData;
